### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kwoot** [kdheepak/taskwarrior-tui#27]
I work on ubuntu 20.04
I did the git clone and cargo build as documented.
I get:
error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/app.rs:394:47
    |
394 |         self.context_name = self.context_name.strip_suffix('\n').unwrap_or("").to_string();
    |                                               ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/app.rs:401:51
    |
401 |         self.context_filter = self.context_filter.strip_suffix('\n').unwrap_or("").to_string();
    |                                                   ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

**To Reproduce**

 git clone https://github.com/kdheepak/taskwarrior-tui.git
 cd taskwarrior-tui/
 cargo build --release
 rustc --explain E0658
 cargo -V
 rustc -V
both at 1.43.0

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: 
- taskwarrior-tui version:

```bash
taskwarrior-tui --version
```
- task version:

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
That is so strange! Maybe it is just the version of rustc?

![Screen Shot 2020-10-27 at 3 35 16 AM](https://user-images.githubusercontent.com/1813121/97283415-6f87b580-1805-11eb-874b-bda14e27e370.png)

**Comment by kdheepak** [comment]
Is it possible for you to update your rust installation?

**Comment by kdheepak** [comment]
Ah, `strip_prefix` and `strip_suffix` were [stabilized](https://github.com/rust-lang/rust/blob/master/RELEASES.md#stabilized-apis-2) in [rust 1.45](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1450-2020-07-16). If you are able to update your rust installation it should work fine.

**Comment by kwoot** [comment]
I am currently using the default package of Ubuntu 20.04. If Rust has some sort of self updatable feature, I would be glad to use. it. 
Ah: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
Done. Compiles. Works!
