### ISSUE TITLE
Compile error from str_strip when compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by kwoot** [kdheepak/taskwarrior-tui#28]
**Describe the bug**
Compile error trying to compile on Ubuntu 20.04

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/app.rs:394:47
    |
394 |         self.context_name = self.context_name.strip_suffix('\n').unwrap_or("").to_string();
    |                                               ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/app.rs:401:51
    |
401 |         self.context_filter = self.context_filter.strip_suffix('\n').unwrap_or("").to_string();
    |                                                   ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

**To Reproduce**

git clone https://github.com/kdheepak/taskwarrior-tui.git
 cd taskwarrior-tui/
 cargo build --release
 rustc --explain E0658
 cargo -V
 rustc -V
Both at version 1.43.0

**Environment (please complete the following information):**

- Operating System: 
- Installation: 
- taskwarrior-tui version:

```bash
taskwarrior-tui --version
```
- task version:

```bash
task --version
```

**Additional context and information**

**Comment by kdheepak** [comment]
Closing since it is a duplicate of #27.

**Comment by MiChatz** [comment]
It wasn't so obvious the solutions for me.  
I will just add some steps in case of anybody else looking for the solution to this issue.  
1.  uninstall rustc `sudo apt remove rustc`  
1.  reinstall rust `curl https://sh.rustup.rs -sSf | bash -s -- -y --no-modify-path`  
1.  add path to your .bashrc `export PATH="$PATH:$HOME/.cargo/bin"`  
1. rebuild

**Comment by kdheepak** [comment]
Thanks for adding the detailed instructions. `rustup` also should have worked I believe.
